{
 "title": "Requests & Responds Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Route Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(url) (changes(minitwit_requests_total{url!=\"/metrics\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "timeseries",
   "description": "Does not include /metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (minitwit_requests_total{url!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http-Methods",
   "type": "timeseries",
   "description": "Does not include /metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (changes(minitwit_requests_total{url!=\"/msgs\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "description": "Does not include /metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(code) (changes(minitwit_requests_total{url!=\"/metrics\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}