{
 "title": "User Actions",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Amount of Posted Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(minitwit_messages_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of Messages Posted (past 7d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by() (rate(minitwit_messages_counter[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly Distribution of Posted Messages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(hour) (minitwit_messages_counter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekdays for Posted Messages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(weekday) (minitwit_messages_counter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Flagged Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "minitwit_flagged_messages_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Users Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by() (minitwit_users_created_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of New Users Created (past 7d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "rate(minitwit_new_users_created[7d])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Followers",
   "type": "bargauge",
   "description": "The amount of followers per user",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_follower_total{range=\"1-500\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"501-1500\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"1501-3000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"3001-6000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"6001-12000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"12001-24000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"24001-48000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_follower_total{range=\"48001-999999\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "User Followees",
   "type": "bargauge",
   "description": "The amount of followers per user",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_followees_total{range=\"1-500\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"501-1500\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"1501-3000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"3001-6000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"6001-12000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"12001-24000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"24001-48000\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "minitwit_followees_total{range=\"48001-999999\"}",
     "legendFormat": "{{range}}"
    }
   ]
  }
 ]
}