# Copied from https://github.com/itu-devops/itu-minitwit-monitoring/blob/function_counters/prometheus.yml 

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 80
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: 'minitwit_app'
        action: keep
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job