networks:
  main:    

services:
  app:
    build: 
      dockerfile: ./Dockerfile
    image: minitwit_image
    container_name: app
    ports:
      - 8000:8000
    networks:
      - main
    depends_on:
      - grafana
      - prometheus
    environment:
      - SNAPSHOT_TIME_INTERVAL_SECONDS=300
      - FOLLOWER_BUCKETS=1-20,21-50,51-100,101-500,501-1500,1501-3000,3001-6000,6001-12000,12001-24000,24001-48000,48001-999999

  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ./.infrastructure/prometheus
    image: prometheus_image
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - main

  alloy:
    build: 
      dockerfile: ./Dockerfile
      context: ./.infrastructure/alloy
    image: alloy_image
    container_name: alloy 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - main
  
  loki:
    build: 
      dockerfile: ./Dockerfile
      context: ./.infrastructure/loki
    image: loki_image
    container_name: loki
    networks:
      - main  

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ./.infrastructure/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"  
    environment:
      - PROMETHEUS_HOST=prometheus:9090
      - LOKI_HOST=loki:3100
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana

  # Database
  database:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minitwit
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  grafana-storage: {}
  pgdata: