name: "minitwit"

services:
  app:
    build: 
      dockerfile: ./Dockerfile
    image: minitwit_image
    ports:
      - 8000:8000
    environment:
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-minitwit}
      - DB_SSL_MODE=${DB_SSL_MODE:-disable}

  # Database
  database:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-minitwit}
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: