networks:
  main:
    name: minitwit-network

services:
  app:
    image: ${DOCKER_USERNAME}/minitwit:monitoringtest
#   image: ${DOCKER_USERNAME}/minitwit:latest
    container_name: app
    ports:
      - 0.0.0.0:80:8000
    networks:
      - main
    depends_on:
      - grafana
      - prometheus
    restart: always
    volumes:
      - sqliteDB:/minitwit/tmp


  prometheus:
    image: ${DOCKER_USERNAME}/prometheus:monitoringtest
#   image: ${DOCKER_USERNAME}/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - main


  grafana:
    image: ${DOCKER_USERNAME}/grafana:monitoringtest
#   image: ${DOCKER_USERNAME}/grafana:latest
    container_name: grafana
    ports:
      - "0.0.0.0:3000:3000"  
    environment:
      - PROMETHEUS_HOST=prometheus:9090
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage: {}
  sqliteDB: {}