services:
  app:
    build: !reset null
    ports:
      - 0.0.0.0:80:8000
    restart: always

  prometheus:
    build: !reset null

  alloy:
    build: !reset null

  loki:
    build: !reset null

  grafana:
    build: !reset null
    volumes:
      - grafana-storage:/var/lib/grafana
    
  database: !reset null


volumes:
  grafana-storage: {}