networks:
  main:
    name: minitwit-network

services:
  app:
    build: 
      dockerfile: ./Dockerfile
    image: minitwit_image
    container_name: app
    volumes:
      - sqliteDB:/minitwit/tmp
    ports:
      - 8000:8000
    networks:
      - main
    depends_on:
      - grafana
      - prometheus


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  sqliteDB:
  grafana-storage: {}