services:
  app:
    build: !reset null
    ports:
      - 0.0.0.0:80:8000
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  prometheus:
    build: !reset null
    ports:
      - "0.0.0.0:9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == manager

  alloy:
    build: !reset null
    deploy:
      placement:
        constraints:
          - node.role == manager

  loki:
    build: !reset null
    ports:
      - "3100:3100"
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    build: !reset null
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.role == manager


volumes:
  grafana-storage: {}