apiVersion: 1

# Inspired by https://community.grafana.com/t/solved-datasource-provisioning-prometheus/6300
datasources:
  - name: prometheus
    type: prometheus
    url: http://${PROMETHEUS_HOST}
    isDefault: true
    editable: false
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: 'http://${LOKI_HOST}'
    limits_config:
      volume-enabled: true