apiVersion: 1

# Inspired by https://community.grafana.com/t/solved-datasource-provisioning-prometheus/6300
datasources:
  - name: prometheus
    type: prometheus
    url: http://${PROMETHEUS_HOST}
    isDefault: true
    editable: false