name: Enhancement-template
description: "This issue is an enhancement to the program"
labels: ["enhancement"]
projects: ["DuwuOps/1"]
body:
  - type: markdown
    attributes:
      value: "## Acceptance Criteria"
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: What is needed for this issue to be complete?
      value: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Problem Description"
  - type: textarea
    attributes:
      label: Problem description
      description: What problem is this issue about?
      placeholder: |        
        > The program does abc
        > 
    validations:
      required: false
