name: Generate report pdf

on:
  push:
    paths:
      - 'report/**'
  pull_request:
    paths:
      - 'report/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_report_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build PDF report
        working-directory: ./report/contents
        run: |
          mkdir -p ../build
          # Preprocess report.md to handle @include statements
          awk '
            /^@include / {
              file = substr($0, 10)
              while ((getline line < file) > 0) print line
              close(file)
              next
            }
            { print }
          ' report.md > ../build/report_full.md
          sed -i 's/\.\.\//\.\.\///g' ../build/report_full.md
          sed -i 's/\.\.\//report\//g' ../build/report_full.md

      - name: Build PDF report with pandoc through Docker
        uses: docker://pandoc/latex:latest
        with:
          args: >-
            --number-sections
            --filter pandoc-crossref
            --citeproc
            --figure-caption-position=below
            --table-caption-position=below
            report/build/report_full.md 
            -o report/build/MSc_group_c.pdf 
            --csl=report/contents/ieee.csl 
            --bibliography=report/contents/main.bib

      - name: Commit and push updated PDF report
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name || github.ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f report/build/MSc_group_c.pdf
          git diff --cached --quiet || git commit -m "Update report PDF"
          BRANCH=$(echo "${BRANCH_NAME}" | sed 's#refs/heads/##')
          echo "Pushing to branch $BRANCH"
          git push origin HEAD:refs/heads/$BRANCH
