name: Generate report pdf

on:
  push:
    paths:
      - 'report/**'
  pull_request:
    paths:
      - 'report/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_report_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra
          
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh
          ghcup install ghc --set
          ghcup install cabal --set
          cabal v2-update
          cabal v2-install --install-method=copy pandoc-cli pandoc-crossref

      - name: Build PDF report
        working-directory: ./report/contents
        run: |
          mkdir -p ../build
          # Preprocess report.md to handle @include statements
          awk '
            /^@include / {
              file = substr($0, 10)
              while ((getline line < file) > 0) print line
              close(file)
              next
            }
            { print }
          ' report.md > ../build/report_full.md
          pandoc --number-sections --filter pandoc-crossref --citeproc ../build/report_full.md -o ../build/MSc_group_c.pdf --csl=./ieee.csl --bibliography=./main.bib

      - name: Commit and push updated PDF report
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name || github.ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f report/build/MSc_group_c.pdf
          git diff --cached --quiet || git commit -m "Update report PDF"
          BRANCH=$(echo "${BRANCH_NAME}" | sed 's#refs/heads/##')
          echo "Pushing to branch $BRANCH"
          git push origin HEAD:refs/heads/$BRANCH
