name: Generate report pdf

on:
  push:
    paths:
      - 'report/**'
  pull_request:
    paths:
      - 'report/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_report_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Pandoc, XeLaTeX, and Symbola font
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra \
            fonts-symbola

          # Install pandoc-crossref that matches Pandoc version
          CROSSREF_VERSION="v0.3.17.0"
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/${CROSSREF_VERSION}/pandoc-crossref-Linux.tar.xz
          tar -xf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /usr/local/bin/
          chmod +x /usr/local/bin/pandoc-crossref
          rm pandoc-crossref-Linux.tar.xz
          rm pandoc-crossref.1


      - name: Build PDF report
        working-directory: ./report/contents
        run: |
          mkdir -p ../build
          # Preprocess report.md to handle @include statements
          awk '
            /^@include / {
              file = substr($0, 10)
              while ((getline line < file) > 0) print line
              close(file)
              next
            }
            { print }
          ' report.md > ../build/report_full.md

          pandoc --number-sections \
                 --filter pandoc-crossref \
                 --citeproc \
                 --pdf-engine=xelatex \
                 -V mainfont="Symbola" \
                 ../build/report_full.md \
                 -o ../build/MSc_group_c.pdf \
                 --csl=./ieee.csl \
                 --bibliography=./main.bib

      - name: Commit and push updated PDF report
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name || github.ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f report/build/MSc_group_c.pdf
          git diff --cached --quiet || git commit -m "Update report PDF"
          BRANCH=$(echo "${BRANCH_NAME}" | sed 's#refs/heads/##')
          echo "Pushing to branch $BRANCH"
          git push origin HEAD:refs/heads/$BRANCH
