---
name: Continuous Deployment

on:
  pull_request:
    # Run workflow every time a PR that targets main is edited.
    types:
      - edited
    branches:
      - main

  workflow_dispatch:
    manual: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Container
      run: |
        docker compose up -d

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest Requests

    - name: Test with refactored_minitwit_tests.py
      run: |
        pytest refactored_minitwit_tests.py

    - name: Test with sim_api_test.py
      run: |
        pytest sim_api_test.py

    - name: Destroy Docker artifacts after tests
      run: |
        docker compose down -v --rmi local
